### PR TITLE
v2 upgrade

### PR DESCRIPTION
**Pull request by npbreland**
I've gone ahead and merged #66 and #62 together to avoid creating a conflict resolution step. This should be the last PR we need to merge for this upgrade!

### CODE REVIEW

**Comment by 1999** [comment]
Legend! Do you want me to publish a new version of the package?

**Comment by npbreland** [comment]
Thanks! Yes, that would be good!

**Comment by 1999** [comment]
Done.

**Comment by npbreland** [comment]
Thank you!

**Pull request merged**
