### PR TITLE
(v2 ALL) Replace deprecated package Request with Node-Fetch; make tests compatible with CouchDB v3; dependency cleanup

### PR DESCRIPTION
**Pull request by npbreland**
- Replaces deprecated request package with node-fetch, which will allow a smoother transition to global fetch when it is no longer experimental.
- Updates dev dependencies including Babel for a clean npm audit
- Removes legacy Node support
- Changes tests to remove assumption of admin party. By default, CouchDB v3 (the current supported version) requires an admin user
- Fixes bug in test "should return promise for createDatabase operation" where the created database was not dropped afterward
- Adds a test for the mango method, and removes the "query" argument from it (seems like there isn't a need for it). Also corrects the example on the README for the mango method.
- **Preserves Common JS and ESM interoperability**

All tests pass in tested Node versions: 14 (LTS), 16 (LTS), 18 (current). Haven't worked with Travis before, but I guessed at the needed changes to the .travis.yml.

I'm new to contributing in the open source community, and I welcome any feedback in my code or approach to this pull request.

### CODE REVIEW

**Comment by 1999** [comment]
This is a great PR! Thank you for it.
The only thing that could make it better: it would be great of all of the changes were made in separate PRs as it would be easier to review them.
Also, it feels to me that this should be a major change as the min version of Node is changed here and this can be a breaking change for some teams.

**Comment by npbreland** [comment]
Thank you for looking at my pull request! Good idea about separate PRs and major version upgrade. I'm working on splitting them up now.

**Comment by npbreland** [comment]
I split them into separate PRs! I hope I didn't totally make a mess of it. I marked all of the ones that go together with (v2): #61, #62, #64, #65, #66. The other two, #60 and #63 could be released on their own. For the ones marked v2, I only really split them up for code review purposes: they shouldn't be released on their own, since they depend on one another to work. I'm leaving this PR open since it contains **all** of the changes. For that reason, once code review is complete (provided everything looks good), **this** branch should be used for testing. If we do decide that we want to merge the PRs separately, some additional work may have to be done to make them independent from one another. (In the future, I will probably start with many smaller PRs that can stand on their own). Thank you again @1999 and let me know if any changes need to be made.

**Comment by 1999** [comment]
Legend!

**Pull request closed without merging**
